name: New Feature Proposal
description: "Deprecated: Issues for feature requests and contributions are now posted at https://github.com/mysql/mysql-server and not here."
body:
  - type: markdown
    attributes:
      value: |
        Issues for feature requests and contributions are now posted at [mysql/mysql-server](https://github.com/mysql/mysql-server and not here.   

  - type: checkboxes
    id: preflight
    attributes:
      label: I undertand that this issue will be closed.
      options:
        - label:  I will file my proposal in mysql-server repo.
          required: true
